### ISSUE TITLE
Eraroj en la unua sekcio

### ISSUE THREAD

**Issue by dazzlepansy** [kingrpaul/philip-k-dick_the-hanging-stranger#2]
Mi tralegis la unuan sekcion, ĝis "Estis korpo. Homa korpo." Mi ja ĝuas la rakonton, kaj dankas vin por la traduko! Jen la eraroj kiujn mi trovis. Mi havas liston kaj ne volas krei tro da raportoj, do mi esperas, ke mi ne ĝenos vin se mi raportos la liston kune.

- [x] "ŝultroj doloris" -> "ŝultroj doloris sin"
- [x] "Estis iĝi malhela" -> "Estis iĝi malhele"
- [x] "lian Pakardo" -> "sian Pakardon"
- [x] "por ruĝa lumo" -> "pro ruĝa lumo"
- [x] "anstataŭi la helpanto" -> "anstataŭi la helpanton"
- [x] "fermi duopo da vendo sin mem" -> "fermi mem duopon da vendoj" 
    - [x]  ("duopo" devas esti akusativa; 
    - [x]   "vendo" estas plurala; 
    - [x]   "sin" estas nur refleksiva pronomo, ne por emfazo; 
        - [x]    mi ne estas certa pri la pozicio de "mem", sed mi ne volas parigi ĝin kun la malĝusta substantivo)
- [x] "Li stiris" -> "Li stiris la aŭton" (transitivaj verboj devas havi objekton)
- [x] "neniom parkedejaj lokoj" -> "neniom da parkspacoj"
- [x] "pasis la malgranda kvadrato" -> "preterpasis la malgrandan kvadraton"
- [x] "Lojso rula malspurigis lia fenestro" -> "Lojson malaltenrulis sian fenestron" (eble "mallevi" anstataŭ "malaltenrulis" --- oni ne devas traduki ĉiun vorton de la angla)
- [x] "starigis elmontraĵoj" -> "starigis elmontraĵojn"
- [x] "li faris U-ĝiro" -> "li faris U-ĝiron"
- [x] "kondukis lia aŭto" -> "kondukis sian aŭton"
- [x] "pasis la parkon" -> "preterpasis la parkon" (Mi ne tute certas pri tiu ĉi, sed mi pensas, ke oni pasas la nokton, ktp. Se oni iras preter parko, oni preterpasas la parkon.)
- [x] "pripensis la malhela fasko" -> "pripensis la malhelan faskon" aŭ "pensis pri la malhela fasko"
- [x] "La kolharoj sur lia kolo legiĝis" -> "Liaj kolharoj stariĝis" aŭ "La haroj sur lia kolo stariĝis" ("kolharoj sur lia kolo" signifas "the neck-hairs on his neck"; mi ne certas kion signifas "legiĝis")
- [x] "li glutis maltrankvile" -> "li ekglutis maltrankvile" ("gluti" estas transitiva kaj devas havi objekton; "ekgluti" estas netransitiva verbo)

Mi estos feliĉa, se mi mem eraros pri io! Mia Esperanto estas neniel perfekta. Sed miaj sugestoj por kontroli kaj korekti la restantajn sekciojn estas:

- Ne forgesu la akusativon.
- Eltrovu ĉu verboj estas transitivaj aŭ ne. Transitivaj verboj devas havi objektojn. Se nenia objekto funkcias, eble troviĝas pli taŭga verbo.
- Zorgu pri "sia" kaj "lia".

**Comment by kingrpaul** [comment]
Item-6: "fermi duopo da vendo sin mem", placed "mem" just after "fermi".

**Comment by kingrpaul** [comment]
Item-8: Settled on, "Estas neniom parkadejaj lokoj" -> "Estis neniom malfermaj lokoj por parki"
Item-9: Settled on, "rula malsuperigis lia fenestro" -> "rulis malalten sian fenestron" & added  to glossary
Item-16: Settled on, "La kolharoj sur lia kolo legiĝis kaj li glutis maltrankvile." -> "La haroj sur lia kolo leviĝis kaj li glutis maltrankvile."

**Comment by kingrpaul** [comment]
d4b223d8d9f67e8ac421baf3182a17771f556ad9
