### ISSUE TITLE
Komentoj

### ISSUE THREAD

**Issue by einarfaa** [kingrpaul/philip-k-dick_the-hanging-stranger#3]
The translation are generally very good and high quality. There are a few misses here and there and I have mentioned them as I encountered them. This is the first two sections. I will continue later.

- [x] " Tiam iu tago li vidis ĝin pendantan sur la urba placo." -> "Iun tagon li vidis ĝin ..." (Mi opinias tiun pli klara: "One day..")
- first section:
  - [x] "Je la kvina" - "Je la kvina horo"
  - [x] "Liaj dorso kaj ŝultroj doloris sin pro fosi grundon el la kelo" -> "Lia dorso kaj ŝultroj doloris ĉar li fosis grundon": Take away 'sin' as 'dolori' is non-transitive and doesn't take an object. Using 'pro' here is like saying that his back and shoulders did the digging (which in some ways isn't wrong). I think using 'ĉar' is better. When mixing a singular and a plural with a possessive that applies to both of them is tricky. I may be wrong, but I would give the plural the number-case of the closest one, but others may disagree with me.
  - [x] "Estis iĝi malhele." -> "Iĝis malhele." or even "Malheliĝis" says the same, but is more elegant.
  - [x] "Navedantoj". I have never seen this word before and had to look it up. 'Navedo' is a bobbin used in weaving. 'Navedi' would be to work with weaving in this manner, but could probably be used figuratively as something going back and forth, but that is pretty advanced. I see EO-wikipedia using it, but I have never encountered this use before. An alternative is "allaboraj irantoj", but it is clumsy. I have searched PIV and ReVo, but found nothing.
  - [x] "Li ĉesigis Sian Pakardo pro ruĝa" -> "Li haltis sian aŭton Pakardon  pro ruĝa": I think 'halti' is cleaner, you should consider clarifying that the Packard is a car, small 's' in 'sia'.
  - [x] "eble eĉ fermi mem duopon da vendoj" -> "eble eĉ mem vendi iom" is more esperantic.
  - [x]  "U-ĝiro". I would suggest "duoncirklo".
  - [x] " Lojso rulis malalten sian fenestro kaj intense vidis ekstere" -> " Lojso rulis malalten sian fenestron kaj intense vidis eksteren"
- Second section:
  - [x] "butonanta lia pingla stria mantelo kun indeco" -> "indece butonanta lian pinglan strian mantelon": I feel this is cleaner, and accussative.
  - [x] "Ĉi tiu estas granda afero, Edo. Mi ne povas nur lasi la ulo starante tie" -> "Ĉi tiu estas granda komercoportuno, Edo. Mi ne povas nur lasi la ulon starante tie" 'Afero' is too abstract. 'Komercoportuno', 'Vendo', or 'Oportuno' is better. And accusative.
  - [x] "Ili certas scii pri ĝi" -> "Ili certe scias pri ĝi"
  - [x] "Fergusono ekiĝis reiniri la butikon" -> "Fergusono ekreeniris la butikon"
  - [x] "hodiaŭ posttagmezze, kiam" -> posttagmeze
  - [x] "Li subpremi sian naŭzon" -> subpremis
  - [x] " Kial li pendantis tie?" : Would using pendadis here be better to emphasize the length he has been hanging?
  - [x] "Kio estas la afero?”. 'Afero' is very abstract. I would prefer 'Ĉu estas problemo?'
  - [x] "Lojso ektiregis mem libera. " -> "Lojso ektiregis sin mem libera.", alternatively "Lojso libertiris sin."
  - [x] "Ĉu vi faras bone, Edo?" : faras -> fartas.
  - [x] "Lojso kriegis, sluktanta preterpasi ilin" -> "luktanta por preterpasi ilin"
  - [x] "Li batalis preter ilin al sia butikon" -> "Li batalis preter ilin al sia butiko"
  - [ ]

**Comment by kingrpaul** [comment]
Item 1.2: 
  - PIV shows _dolori_' as transitive so kept _sin_

Item 1.3: 
 - _Iĝadis malhele_ to express that becoming dark was an ongoing process.
 
Item 1.4:
 - _rapidantaj navedantoj -> homoj rapidantaj al siajn laborejojn_, for readability
 - _malgajaj_ -> _malgajaj-vizaĝaj_ for 'grim-faced'

Item 1.5
 - Li ĉesigis Sian Pakardo pro ruĝa lumo -> Li malŝaltis sian Pakard-aŭton pro ruĝa semaforo
 - Buikon -> Buik-aŭton
 - Ĉevo -> Ĉev-aŭto

Item 2.1
 - butonanta lia pingla stria mantelo kun indeco -> butonanta digne lian pinglan strian mantelon; adverb moved for consistency & _digne_ is a better fit to the original word

Item 2.5
 - _Mi vidis ĝin ĉi-posttagmeze, dum mi eliradis por kafo_

Item 2.8:
 - _Kio misas_ for consistency.

Also: removed the glossary as I am not fully satisfied with it.

**Comment by kingrpaul** [comment]
51f3d7b7b22bd743b6f1188fd3f537419fbf9e3f
