### ISSUE TITLE
Komentoj

### ISSUE THREAD

**Issue by einarfaa** [kingrpaul/philip-k-dick_the-hanging-stranger#4]
- section 3:
  - [x] "la policano havanta la kajero murmuris" -> "la policano havanta la kajeron murmuris" (accusative). Alt: "murmuris la policano kiu havis la kajeron"
  - [x] "La polica aŭto moviĝis rapide en la trafiko, pafiĝanta inter la aŭtoj kaj busoj": 'pafiĝi' isn't a good fit here. I would go for a weaving metaphor, ex. "navedanta".
  - [x] "Li prenis profunda tremanta spiro." -> "Li prenis profundan tremantan spiron" (akuzativo).
  - [x] "Esperon flagris tra lia vizaĝo" -> "Espero flagris tra lia vizaĝo"
  - [x] "Komunistoj aŭ faŝistoj transprenanta.": "puĉintaj" is clearer I think. "Povprenantaj" should also work depending on what you want to emphasize. If you leave it, it should be "transprenantaj".
  - [x] "La lumoj ankoraŭ ne estis ŝaltinta.": "ŝaltintaj" as "lumoj" is plural.
  - [x] "Mi estis sufiĉe ekscititas tie, dum minuto" -> "ekcitita"
  - [x] "Ĉi tio ne devas longe," -> "Ĉi tio ne daŭros longe,"  
  - [x]  "Mi esperas ke ĝi estos mallonge," -> "Mi esperas ke ĝi daŭros mallonge,"
  - [x] "Lojso ektiregis la pordon malfermite" -> "ekpuŝis". 'tiri' would be 'to pull', but I imagine him pushing it open.
  - [x] "rapidigantis dum la lumo ŝanĝiĝis" -> "ekrapidis tra la ŝanĝinta lum-kruco" (I would suggest).
  - [x] "Viro ne povus posedi butikon, funkcii komercejo" -> "Viro ne povus posedi butikon, prizorgi vendejon"
  - [x] "dum dudek jaroj sen ekkonis ĉiujn la policanojn" -> "dum dudek jaroj sen koni ĉiujn policanojn"
  - [x] "en la ekspeda ĉambron kaj trans la malantaŭ pordo" -> "en la ekspedan ĉambron kaj trans la malantaŭan pordon"
  - [x] "Li stumblis per la rubujo" -> "Lin stumbligis la rubujo" alt. "Li stumblis de la rubujo."
  - [x] "ruboetinta": I don't understand this word?
  - [x] "tabuloj kaj ruina skatoloj kaj pneŭoj" -> "tabuloj kaj ruinaj skatoloj kaj pneŭoj"
  - [x] "Neona signoj." -> Neonaj signoj.
  - [x] "Li estis proksima, terura proksima" -> "Li estis proksima, terure proksima"
  - [x] "Preter la platformo pri ŝargi de nutraĵa vendejo" -> "Preter la ŝargplatformo de nutraĵa vendejo"
  - [x] "vendejo suprenis la blanka concreta flanko" -> "vendejo soris la blanka concreta flanko" (alt. "supreniris")
  - [x] "Barita fenestroj" -> "baritaj fenestroj"
  - [x] "Granda concreta muro" -> "granda betona muro" (konkreta means something entirely different).
  - [x] "Li bezonis moviĝi daŭre, atingi pli for de ili." -> "Li bezonis moviĝi daŭre, pli for de ili." alt. "Li bezonis moviĝi daŭre, iri pli for de ili."
  - [x] "mallaŭtita zumo" -> "mallaŭta zumo"
  - [x] "Aferaĉoj, descendanta el la ĉielo, paŭzanta momente super la Urbodomo, flirtanta super ĝi en densa svarmo kaj poste silente faliĝi al la tegmenton.": This sentence doesn't have a verb. Either you use 'estis' which would make all the adjectives describing the Aferaĉoj to be plural too, or you could turn the adjectives into verbs (which I think is preferred). "Aferaĉoj estis, descendantaj el la ĉielo, paŭzantaj momente super la Urbodomo, flirtantaj super ĝi en densa svarmo kaj poste silente falantaj al la tegmenton." alt. "Aferaĉoj descendis el la ĉielo, paŭzis momente super la Urbodomo, flirtis super ĝi en densa svarmo kaj poste silente falis al la tegmenton."
  - [x] "Flirtanta formoj el la ĉielo" -> "Flirtantaj formoj el la ..."
  - [x] "malantaŭ malvigliĝanta barilo" -> "malantaŭ malviglanta barilo"
  - [x] "Ili estis alteriĝanta. Malsuprenanta en grupoj, alteriĝanta sur la tegmento de la Urbodomo kaj malaperiĝanta interne." -> "Ili estis alteriĝantaj. Malsuprenantaj en grupoj, alteriĝantaj sur la tegmento de la Urbodomo kaj malaperiĝantaj interne." (plural) also consider turning adjectives into verbs.
  - [x] "Kiel ia grandega insektoj" -> "Kiel ia grandegaj insektoj"
  - [x] "kaj ek ripozis" -> "kaj ekripozis"
  - [x] "Sur la antaŭ ŝtupoj de la Urbodomo" -> "Sur la antaŭŝtupoj de la Urbodomo"
  - [x] "estis viroj, staranta" -> "estis viroj, starantaj"
  - [x] "Grupoj da viro elvenanta el la konstruaĵo kaj haltanta dum momento antau eniri." -> "Grupo da viroj elvenantaj el la konstruaĵo kaj haltantaj dum momento antau ili eniris."
  - [x] "Li estis vidanta⁠—ilin.| Longtempe Lojso rigardis, kaŭre malantaŭ malvigliĝanta barilo en flako da ŝaŭma skoria akvo." In the original there is a section break between these lines"
  - [x] "Ili estis eksterterana⁠—el iu alia mondo, iu alia dimensio. Glitanta tra ĉi tiu fendeto, ĉi tiu rompaĵo en la ŝelo de la universo. Eniranta tra ĉi tiu breĉo, flugilaj insektoj el alia regno de esti." this should be plural.
  - [x] "Kelkaj moviĝisi al atendanta aŭto." -> "Kelkaj moviĝis al atendanta aŭto."
  - [x] "Ĝi ŝanĝiĝis ĝian opinion kaj turniĝis por sekvi la aliaj" -> "Ĝi ŝanĝiĝis sian opinion kaj turniĝis por sekvi la aliajn"
  - [x] "Eble malhelo ne signifas al ili." -> "Eble malhelo ne limigan ilin."
  - [x] " kaj moviĝis ekster sur la strato" -> "kaj moviĝis eksteren sur la strato"
  - [x] "Ĉe la busaj haltejoj staris antendantajn gropojn." -> "Ĉe la busaj haltejoj staris antendantaj gropoj." (nominativo)
  - [x] "ĝia lumoj ekbrilantaj en la vespera morno." -> "ĝia lumoj ekbrilis en la vespera morno."
  - [x] "Lojso moviĝis anataŭe" -> "Lojso moviĝis antaŭe"
  - [x] "Li puŝis sian vojo inter ilin" -> "Li puŝis sin inter ili"
  - [ ]

**Comment by kingrpaul** [comment]
Item 4: PIV shows _flagri_ as intransitive.
Item 5: _transpren-_ -> _povpren-_ x4; "puĉ-" is cognate with "putch" but PIV emphasizes sudden & violent for this word
Item 10: Per M-W, "yank" means pull, but yes, it seems like a _push_, guessing he used yank for lack of a counterpart word in English
Item 11: "_akceliĝi dum la ŝanĝo de la semafora_"
Item 12: _entreprenon_, more general than _vendejon_ and "more general" seems the author's intent
Item 13: _konatiĝi_; becoming acquainted
Item 16: _sterninta_, "strewn"
Item 26: Original text seems to have been a fragment and, I think, implied an unstated "were." Making it explicit so it won't be jarring in translation & adjectives to verbs seems cleaner.
Item 39: _limigis ilin_

**Other**
Corrections in Imprint.
_malfermaj lokoj_ -> neokupitaj lokoj; "parking places" refers to to those not occupied
_akurate_ -> _sufiĉe frue_; implication is "early enough" vs at the expected time

**Comment by kingrpaul** [comment]
c9d24ce55d61c4807fb17f89d555f0f4f61b2b23

**Comment by kingrpaul** [comment]
Add epubs
ec6bef6c6135256342f2a6ce45a350b1ead975a7
